sudo: required
dist: trusty

language: php

branches:
  only:
    - master

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)